// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyYAML(arg1) {
  return window['go']['main']['App']['ApplyYAML'](arg1);
}

export function DeleteNamespace(arg1) {
  return window['go']['main']['App']['DeleteNamespace'](arg1);
}

export function GetGRPCRouteYAML(arg1, arg2) {
  return window['go']['main']['App']['GetGRPCRouteYAML'](arg1, arg2);
}

export function GetGatewayClassYAML(arg1) {
  return window['go']['main']['App']['GetGatewayClassYAML'](arg1);
}

export function GetGatewayYAML(arg1, arg2) {
  return window['go']['main']['App']['GetGatewayYAML'](arg1, arg2);
}

export function GetHTTPRouteYAML(arg1, arg2) {
  return window['go']['main']['App']['GetHTTPRouteYAML'](arg1, arg2);
}

export function GetNodeUsages() {
  return window['go']['main']['App']['GetNodeUsages']();
}

export function GetPodContainers(arg1, arg2) {
  return window['go']['main']['App']['GetPodContainers'](arg1, arg2);
}

export function GetPodUsages() {
  return window['go']['main']['App']['GetPodUsages']();
}

export function GetPodYAML(arg1, arg2) {
  return window['go']['main']['App']['GetPodYAML'](arg1, arg2);
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function OpenTerminal(arg1) {
  return window['go']['main']['App']['OpenTerminal'](arg1);
}

export function PickKubeconfig() {
  return window['go']['main']['App']['PickKubeconfig']();
}

export function ResetKubeconfig() {
  return window['go']['main']['App']['ResetKubeconfig']();
}

export function SelectResource(arg1) {
  return window['go']['main']['App']['SelectResource'](arg1);
}
