// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetState():Promise<main.AppState>;

export function PickKubeconfig():Promise<main.AppState>;

export function RefreshPods():Promise<main.AppState>;

export function ResetKubeconfig():Promise<main.AppState>;
