// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {kube} from '../models';
import {main} from '../models';

export function ApplyYAML(arg1:string):Promise<kube.ApplyResult>;

export function DeleteNamespace(arg1:string):Promise<void>;

export function GetNodeUsages():Promise<Array<kube.NodeUsage>>;

export function GetPodContainers(arg1:string,arg2:string):Promise<Array<string>>;

export function GetPodUsages():Promise<Array<kube.PodUsage>>;

export function GetPodYAML(arg1:string,arg2:string):Promise<string>;

export function GetState():Promise<main.AppState>;

export function OpenTerminal(arg1:kube.TerminalRequest):Promise<main.TerminalEndpoint>;

export function PickKubeconfig():Promise<main.AppState>;

export function ResetKubeconfig():Promise<main.AppState>;

export function SelectResource(arg1:string):Promise<main.AppState>;
