// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {kube} from '../models';
import {main} from '../models';

export function ApplyYAML(arg1:string):Promise<kube.ApplyResult>;

export function GetPodYAML(arg1:string,arg2:string):Promise<string>;

export function GetState():Promise<main.AppState>;

export function PickKubeconfig():Promise<main.AppState>;

export function ResetKubeconfig():Promise<main.AppState>;

export function SelectResource(arg1:string):Promise<main.AppState>;
