// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyYAML(arg1) {
  return window['go']['main']['App']['ApplyYAML'](arg1);
}

export function GetPodYAML(arg1, arg2) {
  return window['go']['main']['App']['GetPodYAML'](arg1, arg2);
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function PickKubeconfig() {
  return window['go']['main']['App']['PickKubeconfig']();
}

export function ResetKubeconfig() {
  return window['go']['main']['App']['ResetKubeconfig']();
}

export function SelectResource(arg1) {
  return window['go']['main']['App']['SelectResource'](arg1);
}
